### ISSUE TITLE
Add /api to show swagger endpoint

### ISSUE THREAD

**Issue by ripwin** [heig-vd-iot2018/back-end#7]

**Comment by ludelafo** [comment]
https://github.com/swagger-api/swagger-ui
Suffit de copier le dossier `dist/` et de configurer dans `index.html` ou alors tu appelles le script dans un endpoint

**Comment by ripwin** [comment]
Etant donné que le but est d'avoir les endpoints sur Github, j'ai ajouté de swagger-markdown au lieu d'utiliser le dossier `dist/`

**Comment by ripwin** [comment]
#12
